
package vista;

/**
 *
 * @author XoanOuteiro
 */
public class AcademiaMasUI extends javax.swing.JFrame {

    /**
     * Creates new form AcademiaMasUI
     */
    public AcademiaMasUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jdlgAltaAlumnos = new javax.swing.JDialog();
        lblAltaAlumnos = new javax.swing.JLabel();
        pnlAltaAlumno = new javax.swing.JPanel();
        lblNombre = new javax.swing.JLabel();
        lblLocalidad = new javax.swing.JLabel();
        txtfNombre = new javax.swing.JTextField();
        txtfLocalidad = new javax.swing.JTextField();
        lblModulos = new javax.swing.JLabel();
        cbbModulos = new javax.swing.JComboBox<>();
        btnGrabar = new javax.swing.JButton();
        btnLimpiar = new javax.swing.JButton();
        btnQuitar = new javax.swing.JButton();
        jscrListContainer = new javax.swing.JScrollPane();
        jlstModulos = new javax.swing.JList<>();
        jdlgBuscarAlumnos = new javax.swing.JDialog();
        lblNombreABuscar = new javax.swing.JLabel();
        txtfNombreABuscar = new javax.swing.JTextField();
        btnMostrar = new javax.swing.JButton();
        pnlContainerDatosAlumno = new javax.swing.JPanel();
        lblVerNombre = new javax.swing.JLabel();
        lblVerLocalidad = new javax.swing.JLabel();
        lblHoras = new javax.swing.JLabel();
        lblContainerNombre = new javax.swing.JLabel();
        lblContainerLocalidad = new javax.swing.JLabel();
        lblContainerHoras = new javax.swing.JLabel();
        lblVerModulos = new javax.swing.JLabel();
        jscrlpContainerDatosModulos = new javax.swing.JScrollPane();
        jlstModulosDatos = new javax.swing.JList<>();
        jdlgAltaModulos = new javax.swing.JDialog();
        lblAltaModulo = new javax.swing.JLabel();
        pnlAltaModulo = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtfNombreModulo = new javax.swing.JTextField();
        txtfHorasModulo = new javax.swing.JTextField();
        txtfUnidadesModulo = new javax.swing.JTextField();
        btnGrabarModulo = new javax.swing.JButton();
        btnLimpiarModulo = new javax.swing.JButton();
        pnlButtonHold = new javax.swing.JPanel();
        btnAddAlumno = new javax.swing.JButton();
        btnAddModulo = new javax.swing.JButton();
        btnSeeAlumno = new javax.swing.JButton();
        menuMainWindow = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();

        jdlgAltaAlumnos.setResizable(false);

        lblAltaAlumnos.setText("ALTA ALUMNOS");

        pnlAltaAlumno.setBorder(javax.swing.BorderFactory.createTitledBorder("Añadir Alumno"));

        lblNombre.setText("Nombre:");

        lblLocalidad.setText("Localidad:");

        javax.swing.GroupLayout pnlAltaAlumnoLayout = new javax.swing.GroupLayout(pnlAltaAlumno);
        pnlAltaAlumno.setLayout(pnlAltaAlumnoLayout);
        pnlAltaAlumnoLayout.setHorizontalGroup(
            pnlAltaAlumnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlAltaAlumnoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlAltaAlumnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlAltaAlumnoLayout.createSequentialGroup()
                        .addComponent(lblNombre)
                        .addGap(18, 18, 18)
                        .addComponent(txtfNombre))
                    .addGroup(pnlAltaAlumnoLayout.createSequentialGroup()
                        .addComponent(lblLocalidad)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtfLocalidad)))
                .addContainerGap())
        );
        pnlAltaAlumnoLayout.setVerticalGroup(
            pnlAltaAlumnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlAltaAlumnoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlAltaAlumnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNombre)
                    .addComponent(txtfNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlAltaAlumnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtfLocalidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblLocalidad))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        lblModulos.setText("Módulos:");

        btnGrabar.setText("Grabar");

        btnLimpiar.setText("Limpiar");
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarActionPerformed(evt);
            }
        });

        btnQuitar.setText("Quitar");

        jscrListContainer.setViewportView(jlstModulos);

        javax.swing.GroupLayout jdlgAltaAlumnosLayout = new javax.swing.GroupLayout(jdlgAltaAlumnos.getContentPane());
        jdlgAltaAlumnos.getContentPane().setLayout(jdlgAltaAlumnosLayout);
        jdlgAltaAlumnosLayout.setHorizontalGroup(
            jdlgAltaAlumnosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jdlgAltaAlumnosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jdlgAltaAlumnosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(lblAltaAlumnos, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlAltaAlumno, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jdlgAltaAlumnosLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(jdlgAltaAlumnosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jdlgAltaAlumnosLayout.createSequentialGroup()
                                .addComponent(lblModulos)
                                .addGap(59, 59, 59)
                                .addComponent(cbbModulos, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jdlgAltaAlumnosLayout.createSequentialGroup()
                                .addComponent(btnGrabar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 80, Short.MAX_VALUE)
                                .addComponent(btnLimpiar)
                                .addGap(10, 10, 10))))
                    .addComponent(jscrListContainer, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addComponent(btnQuitar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jdlgAltaAlumnosLayout.setVerticalGroup(
            jdlgAltaAlumnosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jdlgAltaAlumnosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblAltaAlumnos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pnlAltaAlumno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jdlgAltaAlumnosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblModulos)
                    .addComponent(cbbModulos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jdlgAltaAlumnosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnQuitar)
                    .addComponent(jscrListContainer, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jdlgAltaAlumnosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnGrabar)
                    .addComponent(btnLimpiar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jdlgBuscarAlumnos.setResizable(false);

        lblNombreABuscar.setText("Nombre a buscar:");

        btnMostrar.setText("Mostrar");

        pnlContainerDatosAlumno.setBorder(javax.swing.BorderFactory.createTitledBorder("Datos del alumno"));

        lblVerNombre.setText("Nombre:");

        lblVerLocalidad.setText("Localidad:");

        lblHoras.setText("Horas:");

        lblContainerNombre.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lblContainerLocalidad.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lblContainerHoras.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout pnlContainerDatosAlumnoLayout = new javax.swing.GroupLayout(pnlContainerDatosAlumno);
        pnlContainerDatosAlumno.setLayout(pnlContainerDatosAlumnoLayout);
        pnlContainerDatosAlumnoLayout.setHorizontalGroup(
            pnlContainerDatosAlumnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlContainerDatosAlumnoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlContainerDatosAlumnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlContainerDatosAlumnoLayout.createSequentialGroup()
                        .addComponent(lblVerNombre)
                        .addGap(18, 18, 18)
                        .addComponent(lblContainerNombre, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(pnlContainerDatosAlumnoLayout.createSequentialGroup()
                        .addComponent(lblHoras)
                        .addGap(32, 32, 32)
                        .addComponent(lblContainerHoras, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(pnlContainerDatosAlumnoLayout.createSequentialGroup()
                        .addComponent(lblVerLocalidad)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblContainerLocalidad, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        pnlContainerDatosAlumnoLayout.setVerticalGroup(
            pnlContainerDatosAlumnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlContainerDatosAlumnoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlContainerDatosAlumnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblVerNombre)
                    .addComponent(lblContainerNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(pnlContainerDatosAlumnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblVerLocalidad)
                    .addComponent(lblContainerLocalidad, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addGroup(pnlContainerDatosAlumnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblHoras, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblContainerHoras, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18))
        );

        lblVerModulos.setText("Módulos:");

        jscrlpContainerDatosModulos.setViewportView(jlstModulosDatos);

        javax.swing.GroupLayout jdlgBuscarAlumnosLayout = new javax.swing.GroupLayout(jdlgBuscarAlumnos.getContentPane());
        jdlgBuscarAlumnos.getContentPane().setLayout(jdlgBuscarAlumnosLayout);
        jdlgBuscarAlumnosLayout.setHorizontalGroup(
            jdlgBuscarAlumnosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jdlgBuscarAlumnosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jdlgBuscarAlumnosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jdlgBuscarAlumnosLayout.createSequentialGroup()
                        .addComponent(lblVerModulos)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jscrlpContainerDatosModulos, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                    .addComponent(pnlContainerDatosAlumno, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jdlgBuscarAlumnosLayout.createSequentialGroup()
                        .addComponent(lblNombreABuscar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtfNombreABuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnMostrar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jdlgBuscarAlumnosLayout.setVerticalGroup(
            jdlgBuscarAlumnosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jdlgBuscarAlumnosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jdlgBuscarAlumnosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jdlgBuscarAlumnosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtfNombreABuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnMostrar))
                    .addComponent(lblNombreABuscar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlContainerDatosAlumno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jdlgBuscarAlumnosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jdlgBuscarAlumnosLayout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addComponent(lblVerModulos))
                    .addGroup(jdlgBuscarAlumnosLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jscrlpContainerDatosModulos, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jdlgAltaModulos.setResizable(false);

        lblAltaModulo.setText("ALTA MÓDULOS");

        pnlAltaModulo.setBorder(javax.swing.BorderFactory.createTitledBorder("Añadir Módulo"));

        jLabel2.setText("Nombre:");

        jLabel3.setText("Horas:");

        jLabel4.setText("Unidades:");

        javax.swing.GroupLayout pnlAltaModuloLayout = new javax.swing.GroupLayout(pnlAltaModulo);
        pnlAltaModulo.setLayout(pnlAltaModuloLayout);
        pnlAltaModuloLayout.setHorizontalGroup(
            pnlAltaModuloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlAltaModuloLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlAltaModuloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(pnlAltaModuloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtfNombreModulo)
                    .addComponent(txtfHorasModulo)
                    .addComponent(txtfUnidadesModulo, javax.swing.GroupLayout.DEFAULT_SIZE, 222, Short.MAX_VALUE))
                .addContainerGap())
        );
        pnlAltaModuloLayout.setVerticalGroup(
            pnlAltaModuloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlAltaModuloLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlAltaModuloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtfNombreModulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                .addGroup(pnlAltaModuloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtfHorasModulo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(pnlAltaModuloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel4)
                    .addComponent(txtfUnidadesModulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        btnGrabarModulo.setText("Grabar");

        btnLimpiarModulo.setText("Limpiar");
        btnLimpiarModulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarModuloActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jdlgAltaModulosLayout = new javax.swing.GroupLayout(jdlgAltaModulos.getContentPane());
        jdlgAltaModulos.getContentPane().setLayout(jdlgAltaModulosLayout);
        jdlgAltaModulosLayout.setHorizontalGroup(
            jdlgAltaModulosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jdlgAltaModulosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jdlgAltaModulosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jdlgAltaModulosLayout.createSequentialGroup()
                        .addComponent(btnGrabarModulo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnLimpiarModulo))
                    .addComponent(pnlAltaModulo, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jdlgAltaModulosLayout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(lblAltaModulo)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jdlgAltaModulosLayout.setVerticalGroup(
            jdlgAltaModulosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jdlgAltaModulosLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(lblAltaModulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pnlAltaModulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jdlgAltaModulosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnGrabarModulo)
                    .addComponent(btnLimpiarModulo))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnAddAlumno.setText("Añadir Alumno");
        btnAddAlumno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddAlumnoActionPerformed(evt);
            }
        });

        btnAddModulo.setText("Añadir Módulo");
        btnAddModulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddModuloActionPerformed(evt);
            }
        });

        btnSeeAlumno.setText("Ver Alumno");
        btnSeeAlumno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSeeAlumnoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlButtonHoldLayout = new javax.swing.GroupLayout(pnlButtonHold);
        pnlButtonHold.setLayout(pnlButtonHoldLayout);
        pnlButtonHoldLayout.setHorizontalGroup(
            pnlButtonHoldLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlButtonHoldLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlButtonHoldLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnSeeAlumno, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAddAlumno)
                    .addComponent(btnAddModulo))
                .addContainerGap(149, Short.MAX_VALUE))
        );
        pnlButtonHoldLayout.setVerticalGroup(
            pnlButtonHoldLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlButtonHoldLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnAddAlumno)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnAddModulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSeeAlumno)
                .addContainerGap(139, Short.MAX_VALUE))
        );

        jMenu1.setText("Alumnos");
        menuMainWindow.add(jMenu1);

        jMenu2.setText("Módulos");
        menuMainWindow.add(jMenu2);

        setJMenuBar(menuMainWindow);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlButtonHold, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlButtonHold, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddAlumnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddAlumnoActionPerformed

        this.jdlgAltaAlumnos.setVisible(true);
        this.jdlgAltaAlumnos.setSize(this.jdlgAltaAlumnos.getPreferredSize());
        
    }//GEN-LAST:event_btnAddAlumnoActionPerformed

    private void btnAddModuloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddModuloActionPerformed
                
        this.jdlgAltaModulos.setVisible(true);
        this.jdlgAltaModulos.setSize(this.jdlgAltaModulos.getPreferredSize());
        
    }//GEN-LAST:event_btnAddModuloActionPerformed

    private void btnSeeAlumnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSeeAlumnoActionPerformed

        this.jdlgBuscarAlumnos.setVisible(true);
        this.jdlgBuscarAlumnos.setSize(this.jdlgBuscarAlumnos.getPreferredSize());
        
    }//GEN-LAST:event_btnSeeAlumnoActionPerformed

    private void btnLimpiarModuloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarModuloActionPerformed
        
        this.txtfNombreModulo.setText("");
        this.txtfHorasModulo.setText("");
        this.txtfUnidadesModulo.setText("");
        
    }//GEN-LAST:event_btnLimpiarModuloActionPerformed

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
        
        this.txtfNombre.setText("");
        this.txtfLocalidad.setText("");
        
    }//GEN-LAST:event_btnLimpiarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AcademiaMasUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AcademiaMasUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AcademiaMasUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AcademiaMasUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AcademiaMasUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddAlumno;
    private javax.swing.JButton btnAddModulo;
    private javax.swing.JButton btnGrabar;
    private javax.swing.JButton btnGrabarModulo;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JButton btnLimpiarModulo;
    private javax.swing.JButton btnMostrar;
    private javax.swing.JButton btnQuitar;
    private javax.swing.JButton btnSeeAlumno;
    private javax.swing.JComboBox<String> cbbModulos;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JDialog jdlgAltaAlumnos;
    private javax.swing.JDialog jdlgAltaModulos;
    private javax.swing.JDialog jdlgBuscarAlumnos;
    private javax.swing.JList<String> jlstModulos;
    private javax.swing.JList<String> jlstModulosDatos;
    private javax.swing.JScrollPane jscrListContainer;
    private javax.swing.JScrollPane jscrlpContainerDatosModulos;
    private javax.swing.JLabel lblAltaAlumnos;
    private javax.swing.JLabel lblAltaModulo;
    private javax.swing.JLabel lblContainerHoras;
    private javax.swing.JLabel lblContainerLocalidad;
    private javax.swing.JLabel lblContainerNombre;
    private javax.swing.JLabel lblHoras;
    private javax.swing.JLabel lblLocalidad;
    private javax.swing.JLabel lblModulos;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblNombreABuscar;
    private javax.swing.JLabel lblVerLocalidad;
    private javax.swing.JLabel lblVerModulos;
    private javax.swing.JLabel lblVerNombre;
    private javax.swing.JMenuBar menuMainWindow;
    private javax.swing.JPanel pnlAltaAlumno;
    private javax.swing.JPanel pnlAltaModulo;
    private javax.swing.JPanel pnlButtonHold;
    private javax.swing.JPanel pnlContainerDatosAlumno;
    private javax.swing.JTextField txtfHorasModulo;
    private javax.swing.JTextField txtfLocalidad;
    private javax.swing.JTextField txtfNombre;
    private javax.swing.JTextField txtfNombreABuscar;
    private javax.swing.JTextField txtfNombreModulo;
    private javax.swing.JTextField txtfUnidadesModulo;
    // End of variables declaration//GEN-END:variables
}
