package vista;

import controlador.PersistencyHandler;
import java.io.IOException;
import java.util.ArrayList;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import modelo.Alumno;
import modelo.Modulo;

/**
 *
 * @author XoanOuteiro
 */
public class AcademiaMasUI extends javax.swing.JFrame {

    /*
        
        The code that follows is as faithful as possible to the
        provided development guidelines, however, all methods related to 
        external JDialog classes are also in the following lines (instead of their
        own classes) for simplicitys sake. This means JDialog summoning is done 
        assuming that the JDialogs are atributes of this class (which they are)
        via the .showVisible(true) method
    
        For this adaptation some instance atributes needed to be converted
        into method-variabes or are direct references to the target object
        atributes
    
        As it has been mentioned here already, i will not be pin-pointing each
        and every change when it appears in the code
    
     */
    //Class Atributes
    private ArrayList<Alumno> listaAlumnos;
    private ArrayList<Modulo> listaModulos;

    private PersistencyHandler filesys;

    private DefaultListModel dlmModulos = new DefaultListModel();
    private DefaultListModel dlmVerAlumnos = new DefaultListModel();
    
    private ArrayList<Modulo> moduloInsertList;

    /**
     * Creates new form AcademiaMasUI
     */
    public AcademiaMasUI() {
        initComponents();

        saveSystemInit();

    }

    private void saveSystemInit() {
        try {

            this.filesys = new PersistencyHandler();

        } catch (IOException ex) {

            this.summonErrorPop("Error fatal al inicalizar el sistema de guardado, \n sus acciones desapareceran al cerrar el programa: \n" + ex.getLocalizedMessage(), "Error de incio");

        }

        //Init as empty in case of first-time execution
        this.listaAlumnos = new ArrayList();
        this.listaModulos = new ArrayList();

        //Now attempt-or-pass to preload saves if they exist as to avoid accidental overwrites
        try {

            this.listaModulos = this.filesys.retrieveModulos();

        } catch (ClassNotFoundException | IOException ex) {

            try { //We assume the files were empty, so we imprint our empty list template

                this.filesys.writeModulos(this.listaModulos);

            } catch (IOException ex1) {

                //this action cannot fail
            }

        }

        try {   //Separate try statements to avoid breakage

            this.listaAlumnos = this.filesys.retrieveAlumnos();

        } catch (ClassNotFoundException | IOException ex) {

            try { //We assume the files were empty, so we imprint our empty list template

                this.filesys.writeAlumnos(this.listaAlumnos);

            } catch (IOException ex1) {

                //this action cannot fail
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jdlgAltaAlumnos = new javax.swing.JDialog();
        lblAltaAlumnos = new javax.swing.JLabel();
        pnlAltaAlumno = new javax.swing.JPanel();
        lblNombre = new javax.swing.JLabel();
        lblLocalidad = new javax.swing.JLabel();
        txtfNombre = new javax.swing.JTextField();
        txtfLocalidad = new javax.swing.JTextField();
        lblModulos = new javax.swing.JLabel();
        cbbModulos = new javax.swing.JComboBox<>();
        btnGrabar = new javax.swing.JButton();
        btnLimpiar = new javax.swing.JButton();
        btnQuitar = new javax.swing.JButton();
        jscrListContainer = new javax.swing.JScrollPane();
        jlstModulos = new javax.swing.JList<>();
        jdlgBuscarAlumnos = new javax.swing.JDialog();
        lblNombreABuscar = new javax.swing.JLabel();
        txtfNombreABuscar = new javax.swing.JTextField();
        btnMostrar = new javax.swing.JButton();
        pnlContainerDatosAlumno = new javax.swing.JPanel();
        lblVerNombre = new javax.swing.JLabel();
        lblVerLocalidad = new javax.swing.JLabel();
        lblHoras = new javax.swing.JLabel();
        lblContainerNombre = new javax.swing.JLabel();
        lblContainerLocalidad = new javax.swing.JLabel();
        lblContainerHoras = new javax.swing.JLabel();
        lblVerModulos = new javax.swing.JLabel();
        jscrlpContainerDatosModulos = new javax.swing.JScrollPane();
        jlstModulosDatos = new javax.swing.JList<>();
        jdlgAltaModulos = new javax.swing.JDialog();
        lblAltaModulo = new javax.swing.JLabel();
        pnlAltaModulo = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtfNombreModulo = new javax.swing.JTextField();
        txtfHorasModulo = new javax.swing.JTextField();
        txtfUnidadesModulo = new javax.swing.JTextField();
        btnGrabarModulo = new javax.swing.JButton();
        btnLimpiarModulo = new javax.swing.JButton();
        pnlButtonHold = new javax.swing.JPanel();
        btnAddAlumno = new javax.swing.JButton();
        btnAddModulo = new javax.swing.JButton();
        btnSeeAlumno = new javax.swing.JButton();
        menuMainWindow = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        miCargarAlumnos = new javax.swing.JMenuItem();
        miSalvarAlumnos = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        miCargarModulos = new javax.swing.JMenuItem();
        miSalvarModulos = new javax.swing.JMenuItem();

        jdlgAltaAlumnos.setResizable(false);

        lblAltaAlumnos.setText("ALTA ALUMNOS");

        pnlAltaAlumno.setBorder(javax.swing.BorderFactory.createTitledBorder("Añadir Alumno"));

        lblNombre.setText("Nombre:");

        lblLocalidad.setText("Localidad:");

        javax.swing.GroupLayout pnlAltaAlumnoLayout = new javax.swing.GroupLayout(pnlAltaAlumno);
        pnlAltaAlumno.setLayout(pnlAltaAlumnoLayout);
        pnlAltaAlumnoLayout.setHorizontalGroup(
            pnlAltaAlumnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlAltaAlumnoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlAltaAlumnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlAltaAlumnoLayout.createSequentialGroup()
                        .addComponent(lblNombre)
                        .addGap(18, 18, 18)
                        .addComponent(txtfNombre))
                    .addGroup(pnlAltaAlumnoLayout.createSequentialGroup()
                        .addComponent(lblLocalidad)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtfLocalidad)))
                .addContainerGap())
        );
        pnlAltaAlumnoLayout.setVerticalGroup(
            pnlAltaAlumnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlAltaAlumnoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlAltaAlumnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNombre)
                    .addComponent(txtfNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlAltaAlumnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtfLocalidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblLocalidad))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        lblModulos.setText("Módulos:");

        cbbModulos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cbbModulosMouseClicked(evt);
            }
        });
        cbbModulos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbbModulosActionPerformed(evt);
            }
        });

        btnGrabar.setText("Grabar");

        btnLimpiar.setText("Limpiar");
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarActionPerformed(evt);
            }
        });

        btnQuitar.setText("Quitar");

        jscrListContainer.setViewportView(jlstModulos);

        javax.swing.GroupLayout jdlgAltaAlumnosLayout = new javax.swing.GroupLayout(jdlgAltaAlumnos.getContentPane());
        jdlgAltaAlumnos.getContentPane().setLayout(jdlgAltaAlumnosLayout);
        jdlgAltaAlumnosLayout.setHorizontalGroup(
            jdlgAltaAlumnosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jdlgAltaAlumnosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jdlgAltaAlumnosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(lblAltaAlumnos, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlAltaAlumno, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jdlgAltaAlumnosLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(jdlgAltaAlumnosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jdlgAltaAlumnosLayout.createSequentialGroup()
                                .addComponent(lblModulos)
                                .addGap(59, 59, 59)
                                .addComponent(cbbModulos, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jdlgAltaAlumnosLayout.createSequentialGroup()
                                .addComponent(btnGrabar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnLimpiar)
                                .addGap(10, 10, 10))))
                    .addComponent(jscrListContainer, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addComponent(btnQuitar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jdlgAltaAlumnosLayout.setVerticalGroup(
            jdlgAltaAlumnosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jdlgAltaAlumnosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblAltaAlumnos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pnlAltaAlumno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jdlgAltaAlumnosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblModulos)
                    .addComponent(cbbModulos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jdlgAltaAlumnosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnQuitar)
                    .addComponent(jscrListContainer, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jdlgAltaAlumnosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnGrabar)
                    .addComponent(btnLimpiar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jdlgBuscarAlumnos.setResizable(false);

        lblNombreABuscar.setText("Nombre a buscar:");

        btnMostrar.setText("Mostrar");

        pnlContainerDatosAlumno.setBorder(javax.swing.BorderFactory.createTitledBorder("Datos del alumno"));

        lblVerNombre.setText("Nombre:");

        lblVerLocalidad.setText("Localidad:");

        lblHoras.setText("Horas:");

        lblContainerNombre.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lblContainerLocalidad.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lblContainerHoras.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout pnlContainerDatosAlumnoLayout = new javax.swing.GroupLayout(pnlContainerDatosAlumno);
        pnlContainerDatosAlumno.setLayout(pnlContainerDatosAlumnoLayout);
        pnlContainerDatosAlumnoLayout.setHorizontalGroup(
            pnlContainerDatosAlumnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlContainerDatosAlumnoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlContainerDatosAlumnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlContainerDatosAlumnoLayout.createSequentialGroup()
                        .addComponent(lblVerNombre)
                        .addGap(18, 18, 18)
                        .addComponent(lblContainerNombre, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(pnlContainerDatosAlumnoLayout.createSequentialGroup()
                        .addComponent(lblHoras)
                        .addGap(32, 32, 32)
                        .addComponent(lblContainerHoras, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(pnlContainerDatosAlumnoLayout.createSequentialGroup()
                        .addComponent(lblVerLocalidad)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblContainerLocalidad, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        pnlContainerDatosAlumnoLayout.setVerticalGroup(
            pnlContainerDatosAlumnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlContainerDatosAlumnoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlContainerDatosAlumnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblVerNombre)
                    .addComponent(lblContainerNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(pnlContainerDatosAlumnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblVerLocalidad)
                    .addComponent(lblContainerLocalidad, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addGroup(pnlContainerDatosAlumnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblHoras, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblContainerHoras, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18))
        );

        lblVerModulos.setText("Módulos:");

        jscrlpContainerDatosModulos.setViewportView(jlstModulosDatos);

        javax.swing.GroupLayout jdlgBuscarAlumnosLayout = new javax.swing.GroupLayout(jdlgBuscarAlumnos.getContentPane());
        jdlgBuscarAlumnos.getContentPane().setLayout(jdlgBuscarAlumnosLayout);
        jdlgBuscarAlumnosLayout.setHorizontalGroup(
            jdlgBuscarAlumnosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jdlgBuscarAlumnosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jdlgBuscarAlumnosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jdlgBuscarAlumnosLayout.createSequentialGroup()
                        .addComponent(lblVerModulos)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jscrlpContainerDatosModulos, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                    .addComponent(pnlContainerDatosAlumno, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jdlgBuscarAlumnosLayout.createSequentialGroup()
                        .addComponent(lblNombreABuscar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtfNombreABuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnMostrar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jdlgBuscarAlumnosLayout.setVerticalGroup(
            jdlgBuscarAlumnosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jdlgBuscarAlumnosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jdlgBuscarAlumnosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jdlgBuscarAlumnosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtfNombreABuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnMostrar))
                    .addComponent(lblNombreABuscar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlContainerDatosAlumno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jdlgBuscarAlumnosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jdlgBuscarAlumnosLayout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addComponent(lblVerModulos))
                    .addGroup(jdlgBuscarAlumnosLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jscrlpContainerDatosModulos, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jdlgAltaModulos.setResizable(false);

        lblAltaModulo.setText("ALTA MÓDULOS");

        pnlAltaModulo.setBorder(javax.swing.BorderFactory.createTitledBorder("Añadir Módulo"));

        jLabel2.setText("Nombre:");

        jLabel3.setText("Horas:");

        jLabel4.setText("Unidades:");

        javax.swing.GroupLayout pnlAltaModuloLayout = new javax.swing.GroupLayout(pnlAltaModulo);
        pnlAltaModulo.setLayout(pnlAltaModuloLayout);
        pnlAltaModuloLayout.setHorizontalGroup(
            pnlAltaModuloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlAltaModuloLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlAltaModuloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(pnlAltaModuloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtfNombreModulo)
                    .addComponent(txtfHorasModulo)
                    .addComponent(txtfUnidadesModulo, javax.swing.GroupLayout.DEFAULT_SIZE, 222, Short.MAX_VALUE))
                .addContainerGap())
        );
        pnlAltaModuloLayout.setVerticalGroup(
            pnlAltaModuloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlAltaModuloLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlAltaModuloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtfNombreModulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                .addGroup(pnlAltaModuloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtfHorasModulo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(pnlAltaModuloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel4)
                    .addComponent(txtfUnidadesModulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        btnGrabarModulo.setText("Grabar");
        btnGrabarModulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGrabarModuloActionPerformed(evt);
            }
        });

        btnLimpiarModulo.setText("Limpiar");
        btnLimpiarModulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarModuloActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jdlgAltaModulosLayout = new javax.swing.GroupLayout(jdlgAltaModulos.getContentPane());
        jdlgAltaModulos.getContentPane().setLayout(jdlgAltaModulosLayout);
        jdlgAltaModulosLayout.setHorizontalGroup(
            jdlgAltaModulosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jdlgAltaModulosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jdlgAltaModulosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jdlgAltaModulosLayout.createSequentialGroup()
                        .addComponent(btnGrabarModulo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnLimpiarModulo))
                    .addComponent(pnlAltaModulo, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jdlgAltaModulosLayout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(lblAltaModulo)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jdlgAltaModulosLayout.setVerticalGroup(
            jdlgAltaModulosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jdlgAltaModulosLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(lblAltaModulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlAltaModulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jdlgAltaModulosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnGrabarModulo)
                    .addComponent(btnLimpiarModulo))
                .addContainerGap(18, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnAddAlumno.setText("Añadir Alumno");
        btnAddAlumno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddAlumnoActionPerformed(evt);
            }
        });

        btnAddModulo.setText("Añadir Módulo");
        btnAddModulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddModuloActionPerformed(evt);
            }
        });

        btnSeeAlumno.setText("Ver Alumno");
        btnSeeAlumno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSeeAlumnoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlButtonHoldLayout = new javax.swing.GroupLayout(pnlButtonHold);
        pnlButtonHold.setLayout(pnlButtonHoldLayout);
        pnlButtonHoldLayout.setHorizontalGroup(
            pnlButtonHoldLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlButtonHoldLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlButtonHoldLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnSeeAlumno, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAddAlumno)
                    .addComponent(btnAddModulo))
                .addContainerGap(149, Short.MAX_VALUE))
        );
        pnlButtonHoldLayout.setVerticalGroup(
            pnlButtonHoldLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlButtonHoldLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnAddAlumno)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnAddModulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSeeAlumno)
                .addContainerGap(139, Short.MAX_VALUE))
        );

        jMenu1.setText("Alumnos");

        miCargarAlumnos.setText("Cargar");
        miCargarAlumnos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miCargarAlumnosActionPerformed(evt);
            }
        });
        jMenu1.add(miCargarAlumnos);

        miSalvarAlumnos.setText("Salvar");
        miSalvarAlumnos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miSalvarAlumnosActionPerformed(evt);
            }
        });
        jMenu1.add(miSalvarAlumnos);

        menuMainWindow.add(jMenu1);

        jMenu2.setText("Módulos");

        miCargarModulos.setText("Cargar");
        miCargarModulos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miCargarModulosActionPerformed(evt);
            }
        });
        jMenu2.add(miCargarModulos);

        miSalvarModulos.setText("Salvar");
        miSalvarModulos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miSalvarModulosActionPerformed(evt);
            }
        });
        jMenu2.add(miSalvarModulos);

        menuMainWindow.add(jMenu2);

        setJMenuBar(menuMainWindow);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlButtonHold, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlButtonHold, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddAlumnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddAlumnoActionPerformed

        this.jdlgAltaAlumnos.setVisible(true);
        this.jdlgAltaAlumnos.setSize(this.jdlgAltaAlumnos.getPreferredSize());

        this.setComboBox();

    }//GEN-LAST:event_btnAddAlumnoActionPerformed

    private void setComboBox() {
        //Load Modulos to combobox

        this.cbbModulos.removeAllItems();

        for (Modulo m : this.listaModulos) {

            this.cbbModulos.addItem(m.getNombre());

        }
    }

    private void btnAddModuloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddModuloActionPerformed

        this.jdlgAltaModulos.setVisible(true);
        this.jdlgAltaModulos.setSize(this.jdlgAltaModulos.getPreferredSize());

    }//GEN-LAST:event_btnAddModuloActionPerformed

    private void btnSeeAlumnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSeeAlumnoActionPerformed

        this.jdlgBuscarAlumnos.setVisible(true);
        this.jdlgBuscarAlumnos.setSize(this.jdlgBuscarAlumnos.getPreferredSize());

    }//GEN-LAST:event_btnSeeAlumnoActionPerformed

    private void btnLimpiarModuloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarModuloActionPerformed

        this.txtfNombreModulo.setText("");
        this.txtfHorasModulo.setText("");
        this.txtfUnidadesModulo.setText("");

    }//GEN-LAST:event_btnLimpiarModuloActionPerformed

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed

        this.txtfNombre.setText("");
        this.txtfLocalidad.setText("");
        this.dlmModulos.clear();
        this.jlstModulos.setModel(this.dlmModulos);
        this.cbbModulos.removeAllItems();
        this.setComboBox();

    }//GEN-LAST:event_btnLimpiarActionPerformed

    private void miCargarAlumnosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miCargarAlumnosActionPerformed

        this.reLoadAlumnos();

    }//GEN-LAST:event_miCargarAlumnosActionPerformed

    private void btnGrabarModuloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGrabarModuloActionPerformed

        this.dispose();

    }//GEN-LAST:event_btnGrabarModuloActionPerformed

    private void miCargarModulosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miCargarModulosActionPerformed

        this.reLoadModulos();

    }//GEN-LAST:event_miCargarModulosActionPerformed

    private void miSalvarModulosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miSalvarModulosActionPerformed

        this.saveModulos();

    }//GEN-LAST:event_miSalvarModulosActionPerformed

    private void miSalvarAlumnosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miSalvarAlumnosActionPerformed

        this.saveAlumnos();

    }//GEN-LAST:event_miSalvarAlumnosActionPerformed

    private void cbbModulosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbbModulosActionPerformed


    }//GEN-LAST:event_cbbModulosActionPerformed

    private void cbbModulosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cbbModulosMouseClicked

        try {
            Object modulo1 = this.cbbModulos.getSelectedItem();
            this.loadModuloList(modulo1.toString());
            this.cbbModulos.removeItem(modulo1);
        } catch (NullPointerException e) {
            e.getMessage();
        }

    }//GEN-LAST:event_cbbModulosMouseClicked

    private void loadModuloList(String m) {
        try {

            this.dlmModulos.addElement(m);
            this.jlstModulos.setModel(this.dlmModulos);

        } catch (NullPointerException e) {

            this.summonErrorPop(e.getLocalizedMessage(), "Error en precarga");

        }
    }

    private void saveModulosToAlumnoInsert() {
        
        this.moduloInsertList = new ArrayList();

        for (int cont = 0; cont < this.dlmModulos.size(); cont++) {
            
            for (int cont2 = 0; cont2 < listaModulos.size(); cont2++) {
                
                if (this.dlmModulos.get(cont).equals(listaModulos.get(cont2).getNombre())) {
                    
                    this.moduloInsertList.add(listaModulos.get(cont2));
                    
                }
            }
        }

    }

    private void reLoadModulos() {

        try {

            this.listaModulos = this.filesys.retrieveModulos();

        } catch (ClassNotFoundException | IOException ex) {

            this.summonErrorPop(ex.getLocalizedMessage(), "Error al cargar modulos guardados");

        }

    }

    private void saveModulos() {

        try {

            this.filesys.writeModulos(this.listaModulos);

        } catch (IOException ex) {

            this.summonErrorPop(ex.getLocalizedMessage(), "Error al guardar modulos");

        }

    }

    private void reLoadAlumnos() {

        try {

            this.listaAlumnos = this.filesys.retrieveAlumnos();

        } catch (ClassNotFoundException | IOException ex) {

            this.summonErrorPop(ex.getLocalizedMessage(), "Error al cargar alumnos guardados");

        }

    }

    private void saveAlumnos() {

        try {

            this.filesys.writeAlumnos(this.listaAlumnos);

        } catch (IOException ex) {

            this.summonErrorPop(ex.getLocalizedMessage(), "Error al guardar alumnos");

        }

    }

    @Override
    public void dispose() {

        if (this.checkAltaModuloIsValid()) {

            try {

                this.listaModulos.add(new Modulo(this.txtfNombreModulo.getText(), Integer.parseInt(this.txtfHorasModulo.getText()), Integer.parseInt(this.txtfUnidadesModulo.getText())));
                this.txtfNombreModulo.setText("");
                this.txtfHorasModulo.setText("");
                this.txtfUnidadesModulo.setText("");

            } catch (NumberFormatException e) {

                this.summonErrorPop("Los campos de hora y unidades deben ser numericos", "Error en Alta");

            }

        } else {

            this.summonErrorPop("Los campos de texto no pueden estar vacios", "Error en Alta");

        }

    }

    private boolean checkAltaModuloIsValid() {

        if (this.txtfNombreModulo.getText().equals("") || this.txtfHorasModulo.getText().equals("") || this.txtfUnidadesModulo.getText().equals("")) {

            return false;

        } else {

            return true;

        }

    }

    private void summonErrorPop(String txt, String title) {

        JOptionPane.showMessageDialog(null, txt, title, JOptionPane.WARNING_MESSAGE);

    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AcademiaMasUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AcademiaMasUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AcademiaMasUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AcademiaMasUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AcademiaMasUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddAlumno;
    private javax.swing.JButton btnAddModulo;
    private javax.swing.JButton btnGrabar;
    private javax.swing.JButton btnGrabarModulo;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JButton btnLimpiarModulo;
    private javax.swing.JButton btnMostrar;
    private javax.swing.JButton btnQuitar;
    private javax.swing.JButton btnSeeAlumno;
    private javax.swing.JComboBox<String> cbbModulos;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JDialog jdlgAltaAlumnos;
    private javax.swing.JDialog jdlgAltaModulos;
    private javax.swing.JDialog jdlgBuscarAlumnos;
    private javax.swing.JList<String> jlstModulos;
    private javax.swing.JList<String> jlstModulosDatos;
    private javax.swing.JScrollPane jscrListContainer;
    private javax.swing.JScrollPane jscrlpContainerDatosModulos;
    private javax.swing.JLabel lblAltaAlumnos;
    private javax.swing.JLabel lblAltaModulo;
    private javax.swing.JLabel lblContainerHoras;
    private javax.swing.JLabel lblContainerLocalidad;
    private javax.swing.JLabel lblContainerNombre;
    private javax.swing.JLabel lblHoras;
    private javax.swing.JLabel lblLocalidad;
    private javax.swing.JLabel lblModulos;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblNombreABuscar;
    private javax.swing.JLabel lblVerLocalidad;
    private javax.swing.JLabel lblVerModulos;
    private javax.swing.JLabel lblVerNombre;
    private javax.swing.JMenuBar menuMainWindow;
    private javax.swing.JMenuItem miCargarAlumnos;
    private javax.swing.JMenuItem miCargarModulos;
    private javax.swing.JMenuItem miSalvarAlumnos;
    private javax.swing.JMenuItem miSalvarModulos;
    private javax.swing.JPanel pnlAltaAlumno;
    private javax.swing.JPanel pnlAltaModulo;
    private javax.swing.JPanel pnlButtonHold;
    private javax.swing.JPanel pnlContainerDatosAlumno;
    private javax.swing.JTextField txtfHorasModulo;
    private javax.swing.JTextField txtfLocalidad;
    private javax.swing.JTextField txtfNombre;
    private javax.swing.JTextField txtfNombreABuscar;
    private javax.swing.JTextField txtfNombreModulo;
    private javax.swing.JTextField txtfUnidadesModulo;
    // End of variables declaration//GEN-END:variables
}
