/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ui;

import java.io.File;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.ObjectInput;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.io.Serializable;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import tarefa2.*;
/**
 *
 * @author a22braisdr
 */
public class Interfaz extends javax.swing.JFrame{
    private ArrayList <Alumno> listaAlumnos=new ArrayList<>();
    private ArrayList <Modulo> listaModulos=new ArrayList<>();
    private ArrayList <Modulo> listaModulosAlumno=new ArrayList<>();
    private DefaultListModel modeloLista = new DefaultListModel();
    private DefaultListModel modeloListaAlumno=new DefaultListModel();
    private String alumnos="alumnos.txt";
    private String modulos="modulos.txt";
    private File arquivoAlumnos=new File(alumnos);
    private File arquivoModulos=new File(modulos);
    private ObjectOutputStream guardado;
    private ObjectInputStream cargado;

    /**
     * Creates new form Interfaz
     */
    public Interfaz() {
        initComponents();
        setLocationRelativeTo(null);
        try{
            if(!arquivoAlumnos.exists()){
            arquivoAlumnos.createNewFile();
            }
            if(!arquivoModulos.exists()){
                arquivoModulos.createNewFile();
            }
        }
        catch(IOException e){
            e.getLocalizedMessage();
        }
    }

    public ArrayList<Alumno> getListaAlumnos() {
        return listaAlumnos;
    }

    public void setListaAlumnos(ArrayList<Alumno> listaAlumnos) {
        this.listaAlumnos = listaAlumnos;
    }

    public ArrayList<Modulo> getListaModulos() {
        return listaModulos;
    }

    public void setListaModulos(ArrayList<Modulo> listaModulos) {
        this.listaModulos = listaModulos;
    }

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDEngadirModulo = new javax.swing.JDialog();
        jPanelEngadirModulo = new javax.swing.JPanel();
        lblTituloModulos = new javax.swing.JLabel();
        jPanelOpcionesModulo = new javax.swing.JPanel();
        lblUnidadesModulo = new javax.swing.JLabel();
        jTextFieldNombreModulo = new javax.swing.JTextField();
        lblHorasModulo = new javax.swing.JLabel();
        jTextFieldHorasModulo = new javax.swing.JTextField();
        jTextFieldUnidadesModulo = new javax.swing.JTextField();
        lblNombreModulo = new javax.swing.JLabel();
        btnGrabar = new javax.swing.JButton();
        btnLimpiar = new javax.swing.JButton();
        jDEngadirAlumno = new javax.swing.JDialog();
        jPanelEngadirAlumno = new javax.swing.JPanel();
        lblTituloAlumnos = new javax.swing.JLabel();
        jPanelOpcionesAlumno = new javax.swing.JPanel();
        jTextFieldNombreAlumno = new javax.swing.JTextField();
        lblLocalidad = new javax.swing.JLabel();
        jTextFieldLocalidad = new javax.swing.JTextField();
        lblNombreModulo1 = new javax.swing.JLabel();
        jLabelModuloAlumno = new javax.swing.JLabel();
        jComboBoxModulos = new javax.swing.JComboBox<>();
        btnGrabar1 = new javax.swing.JButton();
        btnLimpiar1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jListModulos = new javax.swing.JList<>();
        btnQuitarModulo = new javax.swing.JButton();
        jDBuscarAlumno = new javax.swing.JDialog();
        jPanelBuscarAlumno = new javax.swing.JPanel();
        lblTituloAlumnos1 = new javax.swing.JLabel();
        jPanelOpcionesBuscarAlumno = new javax.swing.JPanel();
        jTextFieldNombreAlumnoBuscar = new javax.swing.JTextField();
        lblLocalidadBuscar = new javax.swing.JLabel();
        jTextFieldLocalidadBuscar = new javax.swing.JTextField();
        lblNombreAlumnoBuscar = new javax.swing.JLabel();
        jLabelHoras = new javax.swing.JLabel();
        jTextFieldHorasBuscar = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        jListModulosBuscar = new javax.swing.JList<>();
        jLabelModulos = new javax.swing.JLabel();
        jTextFieldNombreBuscar = new javax.swing.JTextField();
        btnBuscar = new javax.swing.JButton();
        jPanelPrincipal = new javax.swing.JPanel();
        jPanelBotones = new javax.swing.JPanel();
        btnVerAlumno = new javax.swing.JButton();
        btnEngadirAlumno = new javax.swing.JButton();
        btnEngadirModulo = new javax.swing.JButton();
        jMenuOpciones = new javax.swing.JMenuBar();
        jMenuAlumnos = new javax.swing.JMenu();
        jMenuItemEngadirAlumno = new javax.swing.JMenuItem();
        jMenuItemVerAlumno = new javax.swing.JMenuItem();
        jMenuItemGuardarAlumno = new javax.swing.JMenuItem();
        jMenuItemCargarAlumnos = new javax.swing.JMenuItem();
        jMenuModulos = new javax.swing.JMenu();
        jMenuItemEngadirModulo = new javax.swing.JMenuItem();
        jMenuItemGuardarModulo = new javax.swing.JMenuItem();
        jMenuItemCargarModulos = new javax.swing.JMenuItem();

        jDEngadirModulo.setTitle("Engadir Módulo");
        jDEngadirModulo.setMinimumSize(new java.awt.Dimension(500, 500));
        jDEngadirModulo.setSize(new java.awt.Dimension(500, 500));
        jDEngadirModulo.setLocationRelativeTo(null);

        lblTituloModulos.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblTituloModulos.setText("Alta Módulos:");

        jPanelOpcionesModulo.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Engadir Módulo", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(51, 102, 255))); // NOI18N

        lblUnidadesModulo.setText("Unidades:");

        lblHorasModulo.setText("Horas:");

        lblNombreModulo.setText("Nombre:");

        javax.swing.GroupLayout jPanelOpcionesModuloLayout = new javax.swing.GroupLayout(jPanelOpcionesModulo);
        jPanelOpcionesModulo.setLayout(jPanelOpcionesModuloLayout);
        jPanelOpcionesModuloLayout.setHorizontalGroup(
            jPanelOpcionesModuloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelOpcionesModuloLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelOpcionesModuloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblNombreModulo)
                    .addComponent(lblUnidadesModulo)
                    .addComponent(lblHorasModulo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                .addGroup(jPanelOpcionesModuloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanelOpcionesModuloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jTextFieldUnidadesModulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jTextFieldNombreModulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jTextFieldHorasModulo, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jPanelOpcionesModuloLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jTextFieldHorasModulo, jTextFieldNombreModulo, jTextFieldUnidadesModulo});

        jPanelOpcionesModuloLayout.setVerticalGroup(
            jPanelOpcionesModuloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelOpcionesModuloLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelOpcionesModuloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNombreModulo)
                    .addComponent(jTextFieldNombreModulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelOpcionesModuloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblHorasModulo)
                    .addComponent(jTextFieldHorasModulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelOpcionesModuloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblUnidadesModulo)
                    .addComponent(jTextFieldUnidadesModulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        btnGrabar.setText("Grabar");
        btnGrabar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGrabarActionPerformed(evt);
            }
        });

        btnLimpiar.setText("Limpiar");
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelEngadirModuloLayout = new javax.swing.GroupLayout(jPanelEngadirModulo);
        jPanelEngadirModulo.setLayout(jPanelEngadirModuloLayout);
        jPanelEngadirModuloLayout.setHorizontalGroup(
            jPanelEngadirModuloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelEngadirModuloLayout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addGroup(jPanelEngadirModuloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelEngadirModuloLayout.createSequentialGroup()
                        .addGroup(jPanelEngadirModuloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanelOpcionesModulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblTituloModulos))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanelEngadirModuloLayout.createSequentialGroup()
                        .addComponent(btnGrabar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 208, Short.MAX_VALUE)
                        .addComponent(btnLimpiar)
                        .addGap(83, 83, 83))))
        );
        jPanelEngadirModuloLayout.setVerticalGroup(
            jPanelEngadirModuloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelEngadirModuloLayout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(lblTituloModulos)
                .addGap(52, 52, 52)
                .addComponent(jPanelOpcionesModulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanelEngadirModuloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnGrabar)
                    .addComponent(btnLimpiar))
                .addContainerGap(206, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jDEngadirModuloLayout = new javax.swing.GroupLayout(jDEngadirModulo.getContentPane());
        jDEngadirModulo.getContentPane().setLayout(jDEngadirModuloLayout);
        jDEngadirModuloLayout.setHorizontalGroup(
            jDEngadirModuloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelEngadirModulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jDEngadirModuloLayout.setVerticalGroup(
            jDEngadirModuloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelEngadirModulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jDEngadirAlumno.setTitle("Engadir Alumno");
        jDEngadirAlumno.setMinimumSize(new java.awt.Dimension(500, 500));
        jDEngadirAlumno.setSize(new java.awt.Dimension(500, 500));
        jDEngadirAlumno.setLocationRelativeTo(null);

        lblTituloAlumnos.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblTituloAlumnos.setText("Alta Alumno:");

        jPanelOpcionesAlumno.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Engadir Alumno", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(51, 102, 255))); // NOI18N

        lblLocalidad.setText("Localidad:");

        lblNombreModulo1.setText("Nombre:");

        jLabelModuloAlumno.setText("Módulos:");

        jComboBoxModulos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jComboBoxModulosMouseClicked(evt);
            }
        });
        jComboBoxModulos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxModulosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelOpcionesAlumnoLayout = new javax.swing.GroupLayout(jPanelOpcionesAlumno);
        jPanelOpcionesAlumno.setLayout(jPanelOpcionesAlumnoLayout);
        jPanelOpcionesAlumnoLayout.setHorizontalGroup(
            jPanelOpcionesAlumnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelOpcionesAlumnoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelOpcionesAlumnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelOpcionesAlumnoLayout.createSequentialGroup()
                        .addGroup(jPanelOpcionesAlumnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblNombreModulo1)
                            .addComponent(lblLocalidad))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                        .addGroup(jPanelOpcionesAlumnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jTextFieldNombreAlumno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldLocalidad, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanelOpcionesAlumnoLayout.createSequentialGroup()
                        .addComponent(jLabelModuloAlumno)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jComboBoxModulos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        jPanelOpcionesAlumnoLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jComboBoxModulos, jTextFieldLocalidad, jTextFieldNombreAlumno});

        jPanelOpcionesAlumnoLayout.setVerticalGroup(
            jPanelOpcionesAlumnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelOpcionesAlumnoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelOpcionesAlumnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNombreModulo1)
                    .addComponent(jTextFieldNombreAlumno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelOpcionesAlumnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblLocalidad)
                    .addComponent(jTextFieldLocalidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelOpcionesAlumnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelModuloAlumno)
                    .addComponent(jComboBoxModulos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        btnGrabar1.setText("Grabar");
        btnGrabar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGrabar1ActionPerformed(evt);
            }
        });

        btnLimpiar1.setText("Limpiar");
        btnLimpiar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiar1ActionPerformed(evt);
            }
        });

        jScrollPane1.setAutoscrolls(true);
        jScrollPane1.setHorizontalScrollBar(null);
        jScrollPane1.setMaximumSize(new java.awt.Dimension(258, 130));
        jScrollPane1.setMinimumSize(new java.awt.Dimension(258, 130));
        jScrollPane1.setWheelScrollingEnabled(false);

        jListModulos.setMaximumSize(new java.awt.Dimension(258, 130));
        jListModulos.setMinimumSize(new java.awt.Dimension(258, 130));
        jListModulos.setPreferredSize(new java.awt.Dimension(258, 130));
        jScrollPane1.setViewportView(jListModulos);

        btnQuitarModulo.setText("Quitar");
        btnQuitarModulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQuitarModuloActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelEngadirAlumnoLayout = new javax.swing.GroupLayout(jPanelEngadirAlumno);
        jPanelEngadirAlumno.setLayout(jPanelEngadirAlumnoLayout);
        jPanelEngadirAlumnoLayout.setHorizontalGroup(
            jPanelEngadirAlumnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelEngadirAlumnoLayout.createSequentialGroup()
                .addGap(74, 74, 74)
                .addGroup(jPanelEngadirAlumnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelEngadirAlumnoLayout.createSequentialGroup()
                        .addComponent(btnGrabar1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnLimpiar1)
                        .addGap(74, 74, 74))
                    .addGroup(jPanelEngadirAlumnoLayout.createSequentialGroup()
                        .addGroup(jPanelEngadirAlumnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelEngadirAlumnoLayout.createSequentialGroup()
                                .addGroup(jPanelEngadirAlumnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanelEngadirAlumnoLayout.createSequentialGroup()
                                        .addComponent(lblTituloAlumnos)
                                        .addGap(99, 99, 99)))
                                .addGap(18, 18, 18)
                                .addComponent(btnQuitarModulo))
                            .addComponent(jPanelOpcionesAlumno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(134, Short.MAX_VALUE))))
        );
        jPanelEngadirAlumnoLayout.setVerticalGroup(
            jPanelEngadirAlumnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelEngadirAlumnoLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(lblTituloAlumnos)
                .addGap(18, 18, 18)
                .addComponent(jPanelOpcionesAlumno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addGroup(jPanelEngadirAlumnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelEngadirAlumnoLayout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
                        .addGroup(jPanelEngadirAlumnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnGrabar1)
                            .addComponent(btnLimpiar1))
                        .addGap(43, 43, 43))
                    .addGroup(jPanelEngadirAlumnoLayout.createSequentialGroup()
                        .addComponent(btnQuitarModulo)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        javax.swing.GroupLayout jDEngadirAlumnoLayout = new javax.swing.GroupLayout(jDEngadirAlumno.getContentPane());
        jDEngadirAlumno.getContentPane().setLayout(jDEngadirAlumnoLayout);
        jDEngadirAlumnoLayout.setHorizontalGroup(
            jDEngadirAlumnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelEngadirAlumno, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jDEngadirAlumnoLayout.setVerticalGroup(
            jDEngadirAlumnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelEngadirAlumno, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jDBuscarAlumno.setTitle("Ver Alumno");
        jDBuscarAlumno.setMinimumSize(new java.awt.Dimension(500, 500));
        jDBuscarAlumno.setSize(new java.awt.Dimension(500, 500));
        jDBuscarAlumno.setLocationRelativeTo(null);

        lblTituloAlumnos1.setText("Nombre a buscar:");

        jPanelOpcionesBuscarAlumno.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Datos del Alumno", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(51, 102, 255))); // NOI18N

        jTextFieldNombreAlumnoBuscar.setEditable(false);

        lblLocalidadBuscar.setText("Localidad:");

        jTextFieldLocalidadBuscar.setEditable(false);

        lblNombreAlumnoBuscar.setText("Nombre:");

        jLabelHoras.setText("Horas:");

        jTextFieldHorasBuscar.setEditable(false);

        javax.swing.GroupLayout jPanelOpcionesBuscarAlumnoLayout = new javax.swing.GroupLayout(jPanelOpcionesBuscarAlumno);
        jPanelOpcionesBuscarAlumno.setLayout(jPanelOpcionesBuscarAlumnoLayout);
        jPanelOpcionesBuscarAlumnoLayout.setHorizontalGroup(
            jPanelOpcionesBuscarAlumnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelOpcionesBuscarAlumnoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelOpcionesBuscarAlumnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelOpcionesBuscarAlumnoLayout.createSequentialGroup()
                        .addGroup(jPanelOpcionesBuscarAlumnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblNombreAlumnoBuscar)
                            .addComponent(lblLocalidadBuscar))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                        .addGroup(jPanelOpcionesBuscarAlumnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jTextFieldNombreAlumnoBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldLocalidadBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanelOpcionesBuscarAlumnoLayout.createSequentialGroup()
                        .addComponent(jLabelHoras)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jTextFieldHorasBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        jPanelOpcionesBuscarAlumnoLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jTextFieldHorasBuscar, jTextFieldLocalidadBuscar, jTextFieldNombreAlumnoBuscar});

        jPanelOpcionesBuscarAlumnoLayout.setVerticalGroup(
            jPanelOpcionesBuscarAlumnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelOpcionesBuscarAlumnoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelOpcionesBuscarAlumnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNombreAlumnoBuscar)
                    .addComponent(jTextFieldNombreAlumnoBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelOpcionesBuscarAlumnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblLocalidadBuscar)
                    .addComponent(jTextFieldLocalidadBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelOpcionesBuscarAlumnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelHoras)
                    .addComponent(jTextFieldHorasBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jScrollPane2.setViewportView(jListModulosBuscar);

        jLabelModulos.setText("Módulos:");

        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelBuscarAlumnoLayout = new javax.swing.GroupLayout(jPanelBuscarAlumno);
        jPanelBuscarAlumno.setLayout(jPanelBuscarAlumnoLayout);
        jPanelBuscarAlumnoLayout.setHorizontalGroup(
            jPanelBuscarAlumnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelBuscarAlumnoLayout.createSequentialGroup()
                .addGap(74, 74, 74)
                .addGroup(jPanelBuscarAlumnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelBuscarAlumnoLayout.createSequentialGroup()
                        .addComponent(jLabelModulos)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(148, 148, 148))
                    .addGroup(jPanelBuscarAlumnoLayout.createSequentialGroup()
                        .addGroup(jPanelBuscarAlumnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanelOpcionesBuscarAlumno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanelBuscarAlumnoLayout.createSequentialGroup()
                                .addComponent(lblTituloAlumnos1)
                                .addGap(34, 34, 34)
                                .addComponent(jTextFieldNombreBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(30, 30, 30)
                                .addComponent(btnBuscar)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanelBuscarAlumnoLayout.setVerticalGroup(
            jPanelBuscarAlumnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelBuscarAlumnoLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(jPanelBuscarAlumnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTituloAlumnos1)
                    .addComponent(jTextFieldNombreBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscar))
                .addGap(50, 50, 50)
                .addComponent(jPanelOpcionesBuscarAlumno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelBuscarAlumnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelModulos))
                .addGap(43, 120, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jDBuscarAlumnoLayout = new javax.swing.GroupLayout(jDBuscarAlumno.getContentPane());
        jDBuscarAlumno.getContentPane().setLayout(jDBuscarAlumnoLayout);
        jDBuscarAlumnoLayout.setHorizontalGroup(
            jDBuscarAlumnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelBuscarAlumno, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jDBuscarAlumnoLayout.setVerticalGroup(
            jDBuscarAlumnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelBuscarAlumno, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("AcademiaMas");
        setLocation(new java.awt.Point(0, 0));

        btnVerAlumno.setText("Ver Alumno");
        btnVerAlumno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerAlumnoActionPerformed(evt);
            }
        });

        btnEngadirAlumno.setText("Engadir Alumno");
        btnEngadirAlumno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEngadirAlumnoActionPerformed(evt);
            }
        });

        btnEngadirModulo.setText("Engadir Módulo");
        btnEngadirModulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEngadirModuloActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelBotonesLayout = new javax.swing.GroupLayout(jPanelBotones);
        jPanelBotones.setLayout(jPanelBotonesLayout);
        jPanelBotonesLayout.setHorizontalGroup(
            jPanelBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelBotonesLayout.createSequentialGroup()
                .addContainerGap(23, Short.MAX_VALUE)
                .addGroup(jPanelBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnVerAlumno)
                    .addComponent(btnEngadirModulo)
                    .addComponent(btnEngadirAlumno))
                .addContainerGap())
        );

        jPanelBotonesLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnEngadirAlumno, btnEngadirModulo, btnVerAlumno});

        jPanelBotonesLayout.setVerticalGroup(
            jPanelBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelBotonesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnEngadirAlumno)
                .addGap(18, 18, 18)
                .addComponent(btnEngadirModulo)
                .addGap(18, 18, 18)
                .addComponent(btnVerAlumno)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanelPrincipalLayout = new javax.swing.GroupLayout(jPanelPrincipal);
        jPanelPrincipal.setLayout(jPanelPrincipalLayout);
        jPanelPrincipalLayout.setHorizontalGroup(
            jPanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelPrincipalLayout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(jPanelBotones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(310, Short.MAX_VALUE))
        );
        jPanelPrincipalLayout.setVerticalGroup(
            jPanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelPrincipalLayout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addComponent(jPanelBotones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(298, Short.MAX_VALUE))
        );

        jMenuAlumnos.setText("Alumnos");

        jMenuItemEngadirAlumno.setText("Engadir Alumno");
        jMenuItemEngadirAlumno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemEngadirAlumnoActionPerformed(evt);
            }
        });
        jMenuAlumnos.add(jMenuItemEngadirAlumno);

        jMenuItemVerAlumno.setText("Ver Alumno");
        jMenuItemVerAlumno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemVerAlumnoActionPerformed(evt);
            }
        });
        jMenuAlumnos.add(jMenuItemVerAlumno);

        jMenuItemGuardarAlumno.setText("Guardar Alumno");
        jMenuItemGuardarAlumno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemGuardarAlumnoActionPerformed(evt);
            }
        });
        jMenuAlumnos.add(jMenuItemGuardarAlumno);

        jMenuItemCargarAlumnos.setText("Cargar Alumnos");
        jMenuItemCargarAlumnos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemCargarAlumnosActionPerformed(evt);
            }
        });
        jMenuAlumnos.add(jMenuItemCargarAlumnos);

        jMenuOpciones.add(jMenuAlumnos);

        jMenuModulos.setText("Módulos");

        jMenuItemEngadirModulo.setText("Engadir Módulo");
        jMenuItemEngadirModulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemEngadirModuloActionPerformed(evt);
            }
        });
        jMenuModulos.add(jMenuItemEngadirModulo);

        jMenuItemGuardarModulo.setText("Guardar Módulo");
        jMenuItemGuardarModulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemGuardarModuloActionPerformed(evt);
            }
        });
        jMenuModulos.add(jMenuItemGuardarModulo);

        jMenuItemCargarModulos.setText("Cargar Módulos");
        jMenuItemCargarModulos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemCargarModulosActionPerformed(evt);
            }
        });
        jMenuModulos.add(jMenuItemCargarModulos);

        jMenuOpciones.add(jMenuModulos);

        setJMenuBar(jMenuOpciones);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItemEngadirAlumnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemEngadirAlumnoActionPerformed
        jDEngadirAlumno.setVisible(true);
        limpiarPanelEngadirAlumno();
        cargarComboBox();
    }//GEN-LAST:event_jMenuItemEngadirAlumnoActionPerformed

    private void btnEngadirAlumnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEngadirAlumnoActionPerformed
        jDEngadirAlumno.setVisible(true);
        limpiarPanelEngadirAlumno();
        cargarComboBox();
    }//GEN-LAST:event_btnEngadirAlumnoActionPerformed

    private void btnEngadirModuloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEngadirModuloActionPerformed
        jDEngadirModulo.setVisible(true);
        limpiarPanelCrearModulo();
    }//GEN-LAST:event_btnEngadirModuloActionPerformed

    private void jMenuItemEngadirModuloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemEngadirModuloActionPerformed
        jDEngadirModulo.setVisible(true);
        limpiarPanelCrearModulo();
    }//GEN-LAST:event_jMenuItemEngadirModuloActionPerformed

    private void btnVerAlumnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerAlumnoActionPerformed
        jDBuscarAlumno.setVisible(true);
        limpiarVerAlumno();
    }//GEN-LAST:event_btnVerAlumnoActionPerformed

    private void jMenuItemVerAlumnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemVerAlumnoActionPerformed
        jDBuscarAlumno.setVisible(true);
        limpiarVerAlumno();
    }//GEN-LAST:event_jMenuItemVerAlumnoActionPerformed

    private void btnGrabarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGrabarActionPerformed
        try{
            String nombreModulo=jTextFieldNombreModulo.getText();
            int unidades=Integer.parseInt(jTextFieldUnidadesModulo.getText());
            int horas=Integer.parseInt(jTextFieldHorasModulo.getText());
            Modulo modulo=new Modulo(unidades, nombreModulo, horas);
            crearModulo(modulo);
            JOptionPane.showMessageDialog(jDEngadirAlumno, "Módulo creado con éxito");
            jDEngadirModulo.setVisible(false);
        }
        catch(NumberFormatException e){
            JOptionPane.showMessageDialog(jDEngadirAlumno, "Unidades y Horas tienen que ser números");
        }
    }//GEN-LAST:event_btnGrabarActionPerformed

    private void btnGrabar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGrabar1ActionPerformed
        try{
            String nombreAlumno=jTextFieldNombreAlumno.getText();
            String localidadAlumno=jTextFieldLocalidad.getText();
            grabarModulosAlumno();
            crearAlumno(nombreAlumno, localidadAlumno,listaModulosAlumno);
            JOptionPane.showMessageDialog(jDEngadirAlumno, "Alumno creado con éxito");
            jDEngadirAlumno.setVisible(false);
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(jDEngadirAlumno, "Erro ao crear o Alumno");
        }
    }//GEN-LAST:event_btnGrabar1ActionPerformed

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
        limpiarPanelCrearModulo();
    }//GEN-LAST:event_btnLimpiarActionPerformed

    private void limpiarVerAlumno() {
        jTextFieldNombreBuscar.setText("");
        jTextFieldNombreAlumnoBuscar.setText("");
        jTextFieldHorasBuscar.setText("");
        jTextFieldLocalidadBuscar.setText("");
        modeloListaAlumno.clear();
        jListModulosBuscar.setModel(modeloListaAlumno);
    }

    private void btnLimpiar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiar1ActionPerformed
        jTextFieldNombreAlumno.setText("");
        jTextFieldLocalidad.setText("");
    }//GEN-LAST:event_btnLimpiar1ActionPerformed

    private void btnQuitarModuloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQuitarModuloActionPerformed
        try{
            int index=jListModulos.getSelectedIndex();
            jComboBoxModulos.addItem(jListModulos.getSelectedValue());
            modeloLista.remove(index);
            jListModulos.setModel(modeloLista);
        }
        catch(IndexOutOfBoundsException e){
            e.getMessage();
        }
    }//GEN-LAST:event_btnQuitarModuloActionPerformed

    private void jComboBoxModulosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxModulosActionPerformed
    }//GEN-LAST:event_jComboBoxModulosActionPerformed

    private void jComboBoxModulosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jComboBoxModulosMouseClicked
        try{
            Object modulo1=jComboBoxModulos.getSelectedItem();
            cargarList(modulo1.toString());
            jComboBoxModulos.removeItem(modulo1);
        }
        catch(NullPointerException e){
            e.getMessage();
        }
    }//GEN-LAST:event_jComboBoxModulosMouseClicked

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        String nombreABuscar=jTextFieldNombreBuscar.getText();
        limpiarVerAlumno();
        for ( Alumno alumno : listaAlumnos ) {
            if (alumno.getNombre().equals(nombreABuscar)){
                jTextFieldNombreAlumnoBuscar.setText(alumno.getNombre());
                jTextFieldHorasBuscar.setText(alumno.getNumeroHoras()+"");
                jTextFieldLocalidadBuscar.setText(alumno.getLocalidad());
                jListModulosBuscar.setModel(cargarListModulosAlumno(alumno));
            }
            
        }
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void jMenuItemGuardarModuloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemGuardarModuloActionPerformed
        iniciarOutput(arquivoModulos);
        try {
            guardado.writeObject(listaModulos);
        } catch (IOException ex) {
            ex.getLocalizedMessage();
        }
        finally {
            try {
                guardado.close();
            } catch (IOException ex) {
                ex.getLocalizedMessage();
            }
        }
    }//GEN-LAST:event_jMenuItemGuardarModuloActionPerformed

    private void jMenuItemGuardarAlumnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemGuardarAlumnoActionPerformed
        iniciarOutput(arquivoAlumnos);
        try {
            guardado.writeObject(listaAlumnos);
        } catch (IOException ex) {
            ex.getLocalizedMessage();
        }
        finally {
            try {
                guardado.close();
            } catch (IOException ex) {
                ex.getLocalizedMessage();
            }
        }
    }//GEN-LAST:event_jMenuItemGuardarAlumnoActionPerformed

    private void jMenuItemCargarAlumnosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemCargarAlumnosActionPerformed
        iniciarInput(arquivoAlumnos);
        try{
            listaAlumnos=(ArrayList)cargado.readObject();
        }
        catch (Exception e){
            e.getLocalizedMessage();
        }
    }//GEN-LAST:event_jMenuItemCargarAlumnosActionPerformed

    private void jMenuItemCargarModulosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemCargarModulosActionPerformed
        iniciarInput(arquivoModulos);
        try{
            listaModulos=(ArrayList)cargado.readObject();
        }
        catch (Exception e){
            e.getLocalizedMessage();
        }
    }//GEN-LAST:event_jMenuItemCargarModulosActionPerformed

    private void crearAlumno(String nombre,String localidad,ArrayList<Modulo> listaModulosAlumno){
        Alumno alumno1=new Alumno(nombre, localidad, listaModulosAlumno);
        listaAlumnos.add(alumno1);
    }
    
    private void crearModulo(Modulo modulo){
        listaModulos.add(modulo);
    }
    
    private void cargarComboBox(){
        try{
            for (Modulo modulo : listaModulos){
                jComboBoxModulos.addItem(modulo.getNombre());
            }
        }
        catch(NullPointerException e){
            e.getStackTrace();
        }
    }
    
    private void cargarList(String modulo){
        try{
            modeloLista.addElement(modulo);
            jListModulos.setModel(modeloLista);
        }
        catch(NullPointerException e){
            e.getStackTrace();
        }
    }
    
    private DefaultListModel cargarListModulosAlumno(Alumno alumno) {
        ArrayList<String> nombresModulos=new ArrayList<>();
        for (int cont=0; cont<alumno.getNombreModulos().length; cont++) {
            nombresModulos.add(alumno.getNombreModulos()[cont]);
        }
        modeloListaAlumno.addAll(nombresModulos);
        return modeloListaAlumno;
    }
    
    private void grabarModulosAlumno() {
        for (int cont=0; cont<modeloLista.size(); cont++) {
            for (int cont2=0; cont2<listaModulos.size(); cont2++) {
                if (modeloLista.get(cont).equals(listaModulos.get(cont2).getNombre())){
                    listaModulosAlumno.add(listaModulos.get(cont2));
                }
            }
        }
    }
    
    private void limpiarPanelEngadirAlumno(){
        jTextFieldNombreAlumno.setText("");
        jTextFieldLocalidad.setText("");
        modeloLista.clear();
        jListModulos.setModel(modeloLista);
        jComboBoxModulos.removeAllItems();
    }
    
    private void limpiarPanelCrearModulo() {
        jTextFieldNombreModulo.setText("");
        jTextFieldUnidadesModulo.setText("");
        jTextFieldHorasModulo.setText("");
    }
    
    private void iniciarOutput(File f) {
        try{
            this.guardado=new ObjectOutputStream(new FileOutputStream(f));
        }
        catch(IOException e){
            e.getLocalizedMessage();
        }
    }
    
    private void iniciarInput(File f) {
        try{
            this.cargado=new ObjectInputStream(new FileInputStream(f)); 
        }
        catch (IOException e){
            e.getLocalizedMessage();
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Interfaz().setVisible(true);
            }
        });
    }

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnEngadirAlumno;
    private javax.swing.JButton btnEngadirModulo;
    private javax.swing.JButton btnGrabar;
    private javax.swing.JButton btnGrabar1;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JButton btnLimpiar1;
    private javax.swing.JButton btnQuitarModulo;
    private javax.swing.JButton btnVerAlumno;
    private javax.swing.JComboBox<String> jComboBoxModulos;
    private javax.swing.JDialog jDBuscarAlumno;
    private javax.swing.JDialog jDEngadirAlumno;
    private javax.swing.JDialog jDEngadirModulo;
    private javax.swing.JLabel jLabelHoras;
    private javax.swing.JLabel jLabelModuloAlumno;
    private javax.swing.JLabel jLabelModulos;
    private javax.swing.JList<String> jListModulos;
    private javax.swing.JList<String> jListModulosBuscar;
    private javax.swing.JMenu jMenuAlumnos;
    private javax.swing.JMenuItem jMenuItemCargarAlumnos;
    private javax.swing.JMenuItem jMenuItemCargarModulos;
    private javax.swing.JMenuItem jMenuItemEngadirAlumno;
    private javax.swing.JMenuItem jMenuItemEngadirModulo;
    private javax.swing.JMenuItem jMenuItemGuardarAlumno;
    private javax.swing.JMenuItem jMenuItemGuardarModulo;
    private javax.swing.JMenuItem jMenuItemVerAlumno;
    private javax.swing.JMenu jMenuModulos;
    private javax.swing.JMenuBar jMenuOpciones;
    private javax.swing.JPanel jPanelBotones;
    private javax.swing.JPanel jPanelBuscarAlumno;
    private javax.swing.JPanel jPanelEngadirAlumno;
    private javax.swing.JPanel jPanelEngadirModulo;
    private javax.swing.JPanel jPanelOpcionesAlumno;
    private javax.swing.JPanel jPanelOpcionesBuscarAlumno;
    private javax.swing.JPanel jPanelOpcionesModulo;
    private javax.swing.JPanel jPanelPrincipal;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField jTextFieldHorasBuscar;
    private javax.swing.JTextField jTextFieldHorasModulo;
    private javax.swing.JTextField jTextFieldLocalidad;
    private javax.swing.JTextField jTextFieldLocalidadBuscar;
    private javax.swing.JTextField jTextFieldNombreAlumno;
    private javax.swing.JTextField jTextFieldNombreAlumnoBuscar;
    private javax.swing.JTextField jTextFieldNombreBuscar;
    private javax.swing.JTextField jTextFieldNombreModulo;
    private javax.swing.JTextField jTextFieldUnidadesModulo;
    private javax.swing.JLabel lblHorasModulo;
    private javax.swing.JLabel lblLocalidad;
    private javax.swing.JLabel lblLocalidadBuscar;
    private javax.swing.JLabel lblNombreAlumnoBuscar;
    private javax.swing.JLabel lblNombreModulo;
    private javax.swing.JLabel lblNombreModulo1;
    private javax.swing.JLabel lblTituloAlumnos;
    private javax.swing.JLabel lblTituloAlumnos1;
    private javax.swing.JLabel lblTituloModulos;
    private javax.swing.JLabel lblUnidadesModulo;
    // End of variables declaration//GEN-END:variables
}
